onlineKredit/onlineKredit.web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace onlineKredit.web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            
            return View();
        }

    }
}

onlineKredit/onlineKredit.web/Controllers/KonsumKreditController.cs
using onlineKredit.freigabe;
using onlineKredit.logic;
using onlineKredit.web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace onlineKredit.web.Controllers
{
    public class KonsumKreditController : Controller
    {
        [HttpGet]
        public ActionResult KreditRahmen()
        {
            Debug.WriteLine("GET - KonsumKredit - KreditRahmen");

            KreditRahmenModel model = new KreditRahmenModel()
            {
                GewünschterBetrag = 25000,  // default Werte
                Laufzeit = 12   // default Werte
            };
            int id = -1;
            if (Request.Cookies["idKunde"] != null && int.TryParse(Request.Cookies["idKunde"].Value, out id))
            {
                /// lade Daten aus Datenbank
                KreditWunsch wunsch = KonsumKreditVerwaltung.KreditRahmenLaden(id);
                model.GewünschterBetrag = (int)wunsch.Betrag.Value;
                model.Laufzeit = wunsch.Laufzeit.Value;
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult KreditRahmen(KreditRahmenModel model)
        {
            Debug.WriteLine("POST - KonsumKredit - KreditRahmen");

            if (ModelState.IsValid)
            {
                /// speichere Daten über BusinessLogic
                if (Request.Cookies["idKunde"] == null)
                {
                    Kunde neuerKunde = KonsumKreditVerwaltung.ErzeugeKunde();

                    if (neuerKunde != null && KonsumKreditVerwaltung.KreditRahmenSpeichern(model.GewünschterBetrag, model.Laufzeit, neuerKunde.ID))
                    {
                        /// ich benötige für alle weiteren Schritte die ID
                        /// des angelegten Kunden. Damit ich diese bei der nächsten Action
                        /// habe, speichere ich sie für diesen Zweck in ein Cookie
                        Response.Cookies.Add(new HttpCookie("idKunde", neuerKunde.ID.ToString()));

                        /// gehe zum nächsten Schritt
                        return RedirectToAction("FinanzielleSituation");
                    }
                }
                else
                {
                    int idKunde = int.Parse(Request.Cookies["idKunde"].Value);

                    if (KonsumKreditVerwaltung.KreditRahmenSpeichern(model.GewünschterBetrag, model.Laufzeit, idKunde))
                    {
                        /// gehe zum nächsten Schritt
                        return RedirectToAction("FinanzielleSituation");
                    }
                }
            }

            /// falls der ModelState NICHT valid ist, bleibe hier und
            /// gib die Daten (falls vorhanden) wieder auf das UI
            return View(model);
        }

        [HttpGet]
        public ActionResult FinanzielleSituation()
        {
            Debug.WriteLine("GET - KonsumKredit - FinanzielleSituation");

            FinanzielleSituationModel model = new FinanzielleSituationModel()
            {
                ID_Kunde = int.Parse(Request.Cookies["idKunde"].Value)
            };

            FinanzielleSituation situation = KonsumKreditVerwaltung.FinanzielleSituationLaden(model.ID_Kunde);
            if (situation != null)
            {
                model.EinkünfteAlimenteUnterhalt = (double)situation.EinkuenfteAlimenteUnterhalt.Value;
                model.NettoEinkommen = (double)situation.MonatsEinkommen.Value;
                model.RatenVerpflichtungen = (double)situation.RatenZahlungen.Value;
                model.UnterhaltsZahlungen = (double)situation.AusgabenALIUNT.Value;
                model.Wohnkosten = (double)situation.Wohnkosten.Value;
            }


            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FinanzielleSituation(FinanzielleSituationModel model)
        {
            Debug.WriteLine("POST - KonsumKredit - FinanzielleSituation");

            if (ModelState.IsValid)
            {
                /// speichere Daten über BusinessLogic
                if (KonsumKreditVerwaltung.FinanzielleSituationSpeichern(
                                                model.NettoEinkommen,
                                                model.RatenVerpflichtungen,
                                                model.Wohnkosten,
                                                model.EinkünfteAlimenteUnterhalt,
                                                model.UnterhaltsZahlungen,
                                                model.ID_Kunde))
                {
                    return RedirectToAction("PersönlicheDaten");
                }
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult PersönlicheDaten()
        {
            Debug.WriteLine("GET - KonsumKredit - PersönlicheDaten");

            List<BildungsModel> alleBildungsAngaben = new List<BildungsModel>();
            List<FamilienStandModel> alleFamilienStandAngaben = new List<FamilienStandModel>();
            List<IdentifikationsModel> alleIdentifikationsAngaben = new List<IdentifikationsModel>();
            List<StaatsbuergerschaftsModel> alleStaatsbuergerschaftsAngaben = new List<StaatsbuergerschaftsModel>();
            List<TitelModel> alleTitelAngaben = new List<TitelModel>();
            List<WohnartModel> alleWohnartAngaben = new List<WohnartModel>();
            List<TitelNachstehendModel> alleTitelNachstehenAngaben = new List<TitelNachstehendModel>();

            /// Lade Daten aus Logic
            foreach (var bildungsAngabe in KonsumKreditVerwaltung.BildungsAngabenLaden())
            {
                alleBildungsAngaben.Add(new BildungsModel()
                {
                    ID = bildungsAngabe.ID.ToString(),
                    Bezeichnung = bildungsAngabe.Bezeichnung
                });
            }

            foreach (var familienStand in KonsumKreditVerwaltung.FamilienStandAngabenLaden())
            {
                alleFamilienStandAngaben.Add(new FamilienStandModel()
                {
                    ID = familienStand.ID.ToString(),
                    Bezeichnung = familienStand.Bezeichnung
                });
            }
            foreach (var identifikationsAngabe in KonsumKreditVerwaltung.IdentifikiationsAngabenLaden())
            {
                alleIdentifikationsAngaben.Add(new IdentifikationsModel()
                {
                    ID = identifikationsAngabe.ID.ToString(),
                    Bezeichnung = identifikationsAngabe.Bezeichnung
                });
            }
            foreach (var land in KonsumKreditVerwaltung.LaenderLaden())
            {
                alleStaatsbuergerschaftsAngaben.Add(new StaatsbuergerschaftsModel()
                {
                    ID = land.ID,
                    Bezeichnung = land.Bezeichnung
                });
            }
            foreach (var titel in KonsumKreditVerwaltung.TitelLaden())
            {
                alleTitelAngaben.Add(new TitelModel()
                {
                    ID = titel.ID.ToString(),
                    Bezeichnung = titel.Bezeichnung
                });
            }
            foreach (var wohnart in KonsumKreditVerwaltung.WohnartenLaden())
            {
                alleWohnartAngaben.Add(new WohnartModel()
                {
                    ID = wohnart.ID.ToString(),
                    Bezeichnung = wohnart.Bezeichnung
                });
            }
            foreach (var titelNachstehend in KonsumKreditVerwaltung.TitelNachstehendLaden())
            {
                alleTitelNachstehenAngaben.Add(new TitelNachstehendModel()
                {
                    ID = titelNachstehend.ID.ToString(),
                    Bezeichnung = titelNachstehend.Bezeichnung
                });
            }


            PersönlicheDatenModel model = new PersönlicheDatenModel()
            {
                AlleBildungAngaben = alleBildungsAngaben,
                AlleFamilienStandAngaben = alleFamilienStandAngaben,
                AlleIdentifikationsAngaben = alleIdentifikationsAngaben,
                AlleStaatsbuergerschaftsAngaben = alleStaatsbuergerschaftsAngaben,
                AlleTitelAngaben = alleTitelAngaben,
                AlleTitelNachstehendAngaben = alleTitelNachstehenAngaben,
                AlleWohnartAngaben = alleWohnartAngaben,
                ID_Kunde = int.Parse(Request.Cookies["idKunde"].Value)
            };

            Kunde kunde = KonsumKreditVerwaltung.PersönlicheDatenLaden(model.ID_Kunde);
            if (kunde != null)
            {
                model.Geschlecht = !string.IsNullOrEmpty(kunde.Gechlecht) && kunde.Gechlecht == "m" ? onlineKredit.web.Models.Geschlecht.Männlich : onlineKredit.web.Models.Geschlecht.Weiblich;
                model.Vorname = kunde.Vorname;
                model.Nachname = kunde.Nachname;
                model.ID_Titel = kunde.FKTitel.HasValue ? kunde.FKTitel.Value : 0;
                model.ID_TitelNachstehend = kunde.FKTitelNachstehend.HasValue ? kunde.FKTitelNachstehend.Value : 0;
                //model.GeburtsDatum = DateTime.Now;
                model.ID_Staatsbuergerschaft = kunde.FKStaatsangehoerigkeit;
                model.ID_Familienstand = kunde.FKFamilienstand.HasValue ? kunde.FKFamilienstand.Value : 0;
                model.ID_Wohnart = kunde.FKWohnart.HasValue ? kunde.FKWohnart.Value : 0;
                model.ID_Bildung = kunde.FKSchulabschluss.HasValue ? kunde.FKSchulabschluss.Value : 0;

onlineKredit/onlineKredit.web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<!--top nav end here-->
<!--banner start here-->
<div class="banner">
</div>
<!--banner end here-->
<!--about-->
<div class="about" id="about">
    <div class="container">
        <div class="col-md-4 about-left">
            <div class="ab-top">
                <h3>100%</h3>
                <h5>Kredit-Rechner</h5>
                <p>Hier geht es rasch und unkompliziert zu Ihrem Wunschkredit.</p>
                @*<a href="#" data-toggle="modal" data-target="#myModal">Mehr Informationen</a>*@
                @Html.ActionLink("Zum Wunschkredit", "KreditRahmen", "KonsumKredit")
            </div>
        </div>
        <div class="col-md-8 about-right">
            <h3>Dienstleistungen</h3>
            <div class="col-md-12 ab-lft">
                <h4>Corporate & Investment Banking</h4>
                <p>
                    Corporate & Investment Banking in Österreich besteht aus den Bereichen Corporate Finance (CF), Debt Capital Markets – Financing & Solutions Group (DCM-FSG) und Global Transaction Banking (GTB).
                    <br /><br />
                    Corporate Finance ist für Fusionen und Übernahmen, die Emission von Anleihen und Aktien sowie die Betreuung von Groß- und Mittelstandsunternehmen im Kapitalmarktgeschäft zuständig. Regionale branchefokussierte Teams stellen sicher, dass den Kunden alle angebotene Finanzierungsprodukte und Serviceleistungen aus einer Hand zur Verfügung stehen.
                    <br /><br />
                    Bitte besuchen Sie unsere Seite für Firmenkunden<br />
                    deutsche Version: <a class="link" href="https://www.db.com/fk/">https://www.db.com/fk/</a>
                </p>
            </div>

            <div class="clearfix"></div>
            <div class="abt-bottom">
                <div class="col-md-6 ab-lft">
                    <h4>Wealth Management</h4>
                    <p>
                        Das Wealth Management der Deutsche Bank Österreich AG betreut vermögende Privatkunden, Familien, Stiftungen und ausgewählte Institutionen und entwickelt darüber hinaus erstklassige Lösungen für Familienunternehmen und unabhängige Vermögensverwalter.<br />
                        <br />
                        Bitte besuchen Sie: <a class="link" href="http://deutschewealth.com/austria/de/index_austria.html">deutschewealth.com/</a>
                    </p>
                </div>
                <div class="col-md-6 ab-lft">
                    <h4>Asset Management</h4>
                    <p>
                        Das Wealth Management der Deutsche Bank Österreich AG betreut vermögende Privatkunden, Familien, Stiftungen und ausgewählte Institutionen und entwickelt darüber hinaus erstklassige Lösungen für Familienunternehmen und unabhängige Vermögensverwalter.<br />
                        <br />
                        Bitte besuchen Sie: <a class="link" href="http://deutschewealth.com/austria/de/index_austria.html">deutschewealth.com/</a>
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="abt-bottom">
                <div class="col-md-10 ab-lft">                  
                        @Html.Action("WerbeBanner", "KonsumKredit")                  
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!--about-->
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Pellentesque vehicula</h4>
            </div>
            <div class="modal-body">
                <p>In varius sem id aliquet rutrum. Pellentesque ut neque ligula. Fusce dapibus volutpat magna, ac feugiat dolor bibendum et. Integer dignissim gravida nunc, eget hendrerit enim. Quisque dapibus mollis finibus. Curabitur nulla enim, aliquet ac ultricies luctus, lacinia ut felis. Etiam aliquam massa nec lorem pulvinar porttitor. Maecenas in rutrum purus, eget consectetur arcu. Sed id pretium ligula, id hendrerit nunc. Nam ut tincidunt erat, sit amet accumsan risus..</p>
            </div>
        </div>
    </div>
</div>
<!--// Modal -->